import IDetailProducts from "./IDetailProducts";

const db: IDetailProducts[] = [
  {id: 1, category: "manga", name: "Steel Ball Run 01", author: "Hirohiko Araki", description: "Llega una de las partes más esperadas de Jojo: Steel Ball Run! Un importante cambio del mundo de Jojo, que reimagina personajes y crea situaciones más locas que nunca ( sí, eso es posible!). La historia nos traslada al año 1890, en la que se va a celebrar una carrera a caballo que atravesará Estados unidos desde San Diego hasta Nueva York llamada Steel Ball Run. Johnny Joestar, un experto jinete que sufrió una herida de bala que lo dejó paralítico, decide participar en ella después de encontrarse con el enigmático Gyro Zeppeli y ver su extraño poder. Su ansia por descubrir el misterio del poder de Gyro, hará que se enfrenten en la carrera, pero pronto tendrán que colaborar para enfrentarse a los duros competidores que les pondrán las cosas más que difíciles.", imgUrl: "http://www.editorialivrea.com/ESP/jojosbizarreadventure/jojo7-steelballrun01.jpg", stock: 10, price: 12},
  {id: 2, category: "manga", name: "Steel Ball Run 02", author: "Hirohiko Araki", description: "Llega una de las partes más esperadas de Jojo: Steel Ball Run! Un importante cambio del mundo de Jojo, que reimagina personajes y crea situaciones más locas que nunca ( sí, eso es posible!). La historia nos traslada al año 1890, en la que se va a celebrar una carrera a caballo que atravesará Estados unidos desde San Diego hasta Nueva York llamada Steel Ball Run. Johnny Joestar, un experto jinete que sufrió una herida de bala que lo dejó paralítico, decide participar en ella después de encontrarse con el enigmático Gyro Zeppeli y ver su extraño poder. Su ansia por descubrir el misterio del poder de Gyro, hará que se enfrenten en la carrera, pero pronto tendrán que colaborar para enfrentarse a los duros competidores que les pondrán las cosas más que difíciles.", imgUrl: "http://www.editorialivrea.com/ESP/jojosbizarreadventure/jojo7-steelballrun02.jpg", stock: 10, price: 12},
  {id: 3, category: "manga", name: "Steel Ball Run 03", author: "Hirohiko Araki", description: "Llega una de las partes más esperadas de Jojo: Steel Ball Run! Un importante cambio del mundo de Jojo, que reimagina personajes y crea situaciones más locas que nunca ( sí, eso es posible!). La historia nos traslada al año 1890, en la que se va a celebrar una carrera a caballo que atravesará Estados unidos desde San Diego hasta Nueva York llamada Steel Ball Run. Johnny Joestar, un experto jinete que sufrió una herida de bala que lo dejó paralítico, decide participar en ella después de encontrarse con el enigmático Gyro Zeppeli y ver su extraño poder. Su ansia por descubrir el misterio del poder de Gyro, hará que se enfrenten en la carrera, pero pronto tendrán que colaborar para enfrentarse a los duros competidores que les pondrán las cosas más que difíciles.", imgUrl: "http://www.editorialivrea.com/ESP/jojosbizarreadventure/jojo7-steelballrun03.jpg", stock: 10, price: 12},
  {id: 4, category: "manga", name: "Vagabond 01", author:"Takehiko Inoue", description: "Adaptación al cómic de uno de los clásicos de la literatura japonesa, la novela biográfica de Eiji Yoshikawa: 'Musashi'. cuenta la historia del legendario espadachín Musashi Miyamoto, la figura histórica más importante del Japón en lo que se refiere al desarrollo de las técnicas de lucha con espada. Al comienzo de la historia vemos al protagonista como un violento e iracundo joven llamado Takezo, el cual sobrevive (aun estando del lado perdedor) a una de las batallas más sangrientas de la historia: Sekigahara. Luego de que su vida da un giro gracias a la intervención de un monje llamado Takuan, el joven Takezo cambia su nombre a Musashi y se embarca en una búsqueda de autosuperación personal que lo llevará a enfrentarse con los más grandes expertos de las artes marciales del país. Así poco a poco, con sangre y sudor, va construyendo su propia leyenda, la del verdadero 'vagabundo' más poderoso de todo Japón.", imgUrl: "http://www.editorialivrea.com/ESP/vagabond/vagabond01hs.jpg", stock: 10, price: 10},
  {id: 5, category: "manga", name: "Vagabond 02", author:"Takehiko Inoue", description: "Adaptación al cómic de uno de los clásicos de la literatura japonesa, la novela biográfica de Eiji Yoshikawa: 'Musashi'. cuenta la historia del legendario espadachín Musashi Miyamoto, la figura histórica más importante del Japón en lo que se refiere al desarrollo de las técnicas de lucha con espada. Al comienzo de la historia vemos al protagonista como un violento e iracundo joven llamado Takezo, el cual sobrevive (aun estando del lado perdedor) a una de las batallas más sangrientas de la historia: Sekigahara. Luego de que su vida da un giro gracias a la intervención de un monje llamado Takuan, el joven Takezo cambia su nombre a Musashi y se embarca en una búsqueda de autosuperación personal que lo llevará a enfrentarse con los más grandes expertos de las artes marciales del país. Así poco a poco, con sangre y sudor, va construyendo su propia leyenda, la del verdadero 'vagabundo' más poderoso de todo Japón.", imgUrl: "http://www.editorialivrea.com/ESP/vagabond/vagabond02hs.jpg", stock: 10, price: 10},
  {id: 6, category: "manga", name: "Vagabond 03", author:"Takehiko Inoue", description: "Adaptación al cómic de uno de los clásicos de la literatura japonesa, la novela biográfica de Eiji Yoshikawa: 'Musashi'. cuenta la historia del legendario espadachín Musashi Miyamoto, la figura histórica más importante del Japón en lo que se refiere al desarrollo de las técnicas de lucha con espada. Al comienzo de la historia vemos al protagonista como un violento e iracundo joven llamado Takezo, el cual sobrevive (aun estando del lado perdedor) a una de las batallas más sangrientas de la historia: Sekigahara. Luego de que su vida da un giro gracias a la intervención de un monje llamado Takuan, el joven Takezo cambia su nombre a Musashi y se embarca en una búsqueda de autosuperación personal que lo llevará a enfrentarse con los más grandes expertos de las artes marciales del país. Así poco a poco, con sangre y sudor, va construyendo su propia leyenda, la del verdadero 'vagabundo' más poderoso de todo Japón.", imgUrl: "http://www.editorialivrea.com/ESP/vagabond/vagabond03hs.jpg", stock: 10, price: 10},
  {id: 7, category: "light novel", name: "Reign of the Seven Spellblades 01", author:"Bokuto Uno", description: "FROM A CLASH OF SWORDS, AN UNSHAKABLE BONDSpringtime at Kimberly Magic Academy brings a new batch of first-year students, all bright-eyed and bushy-tailed as they begin their journey to become full-fledged mages. Among these newcomers are Oliver Horn, a studious boy equally skilled with the wand and the blade, and Nanao Hibiya, a strong-willed samurai girl from the distant nation of Yamatsu. The wheels of fate bring these two souls together at Kimberly, where they become both comrades and rivals in equal measure. However, lurking within the academy's halls are countless dangers and dark secrets guaranteed to threaten not only their friendship-but their very lives...",  imgUrl: "https://images-na.ssl-images-amazon.com/images/I/91oCKyrVDVL.jpg", stock: 10, price: 8},
  {id: 8, category: "light novel", name: "Reign of the Seven Spellblades 02", author: "Bokuto Uno", description: "Halfway into the school year, Oliver's and Nanao's magical prowess has garnered them considerable respect from their classmates. Nevertheless, the question remains: Who is the strongest first-year at Kimberly Magic Academy? So begins a battle royal—style tournament to defeat Oliver and Nanao in combat, and many competitors are eager to throw down the gauntlet. Some, however, will use this opportunity to set their own nasty schemes in motion...", imgUrl: "https://images-na.ssl-images-amazon.com/images/I/91DgHAgSxRL.jpg", stock: 10, price: 8},
  {id: 9, category: "light novel", name: "Reign of the Seven Spellblades 03", author:"Bokuto Uno", description:"Pete's abduction at the hands of Ophelia Salvadori's chimeras has the entire academy in a frenzy and Oliver's group reeling. After all, what can a bunch of first-years do to save their friend from Salvadori, who's been “consumed by the spell”? At this pivotal moment, a certain someone offers a deal to help rescue Pete from the witch holding him captive within the depths of the school's perilous labyrinth…but will Oliver and his classmates succeed in their desperate mission and live to tell the tale?", imgUrl: "https://img.game-news24.com/2021/09/Reign-of-the-Seven-Spellblades-Volume-3-Review.jpeg", stock: 10, price: 8}
]

class ProductsFetch {
  static getProducts(): Promise<IDetailProducts[]> {
    return new Promise (resolve => {
      setTimeout(() => {
        resolve(db)
      }, 2000)
    });
  }

  static getProductsById(id: number): Promise<IDetailProducts | undefined> {
    return new Promise (resolve => {
      setTimeout(() => {
        resolve(db.find(product => product.id === id))
      }, 2000)
    });
  }
}

export default ProductsFetch